name: r2a
dependencies:
 - pip
 - pytorch=0.4.1
 - numpy=1.15.1
 - termcolor=1.1.0
 - tqdm=4.24.0
 - scikit-learn=0.19.2
 - spacy=2.0.12
 - pandas
 - matplotlib
 - pip:
    - torchtext==0.2.1
    - colored==1.3.5
